(define (problem task)
(:domain turtlebot)
(:objects
    wp0 - sky
    wp1 wp2 wp3 wp4 wp5 wp6 wp7 wp8 wp9 - ground
    ugv01 ugv02 ugv03 - ugv
)
(:init
    (ugv_at ugv01 wp1)
    (ugv_at ugv02 wp1)
    (ugv_at ugv03 wp1)

    (connected wp1 wp2)
    (connected wp2 wp1)
    (connected wp2 wp3)
    (connected wp3 wp2)
    (connected wp3 wp4)
    (connected wp4 wp3)
    (connected wp4 wp5)
    (connected wp5 wp4)
    (connected wp5 wp6)
    (connected wp6 wp5)
    (connected wp3 wp4)
    (connected wp4 wp3)
    (connected wp4 wp5)
    (connected wp5 wp4)
    (connected wp5 wp6)
    (connected wp6 wp5)
    (connected wp6 wp7)
    (connected wp7 wp6)
    (connected wp7 wp8)
    (connected wp8 wp7)
    (connected wp8 wp9)
    (connected wp9 wp8)
    (connected wp9 wp0)
    (connected wp0 wp9)
    (connected wp0 wp3)
    (connected wp3 wp0)
    (connected wp3 wp4)
    (connected wp4 wp3)
)
(:goal (and
    (visited wp1)
    (visited wp2)
    (visited wp3)
    (visited wp4)
    (visited wp5)
    (visited wp6)
    (visited wp7)
)))
